language: python
python:
    - 2.7
    - 3.4

git:
    depth: 1000

addons:
    apt:
        packages:
            - texlive
            - texlive-fonts-recommended
            - texlive-latex-extra

install:
    - sudo apt-get install spell
    - pip install sphinx sphinx_rtd_theme

script:
    - spell -n -o -d en_us.ascii.add.spl mef/* | grep -v 'references.rst' > _warnings \
        || echo "no spelling errors!"
    - grep -P -n "[^[:ascii:]]" mef/* | grep -v 'references.rst' >> _warnings \
        || echo "no non-ASCII chars!"
    - make html linkcheck 2>> _warnings
    - cat _warnings && [[ ! -s _warnings ]]
