language: python
python:
    - 2.7
    - 3.4

git:
    depth: 1000

addons:
    apt:
        packages:
            - texlive
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - texlive-latex-extra
            - texlive-xetex
            - lmodern
            - inkscape

install:
    - sudo apt-get install spell
    - pip install sphinx sphinx_rtd_theme

script:
    - grep -P -n "(\t|\s$)" *.rst mef/*.rst >> _warnings || echo "Great, no tabs or trailing spaces!"
    - spell -n -o -d en_us.ascii.add.spl mef/*.rst | grep -v 'bibliography' > _warnings || echo "no spelling errors!"
    - grep -P -n "[^[:ascii:]]" mef/*.rst | grep -v 'bibliography' >> _warnings || echo "no non-ASCII chars!"
    - make latexpdf > /dev/null || echo "Outdated LaTeX on Ubuntu 14.04 :("
    - PYTHONOPTIMIZE=1 make html linkcheck 2>> _warnings
    - cat _warnings && [[ ! -s _warnings ]]
