language: python
python:
    - 2.7
    - 3.3

addons:
    apt:
        packages:
            - dvipng
            - texlive
            - texlive-fonts-recommended
            - texlive-latex-extra

install:
    - sudo apt-get install spell
    - pip install sphinx sphinx_rtd_theme

script:
    - spell -n -o -d en_us.ascii.add.spl mef/* | grep -v '^mef/references.rst'
    - make html linkcheck 2> _warnings.txt
    - cat _warnings.txt && [[ ! -s _warnings.txt ]]
